ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -yqq install --no-install-recommends \
    curl \
    jq \
    moreutils \
    npm \
  && rm -Rf /var/lib/apt/lists/* && \
  npm install --global sloc
