ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG SOURCE_DIR
ARG BUILD_DIR

ARG CMAKE_COMMON_FLAGS
ARG CMAKE_FLAGS
# Provided by the gitlab runner of .container-builder
ARG NUM_PROCS

COPY . ${SOURCE_DIR}

# Configure & Build
RUN spack -e pika_ci build-env $spack_spec -- bash -c \
    "cmake -B${BUILD_DIR} ${SOURCE_DIR} \
    $CMAKE_COMMON_FLAGS $CMAKE_FLAGS && \
    cmake --build ${BUILD_DIR} -j ${NUM_PROCS} --target task_overhead_report_test task_size_test"
