ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG SOURCE_DIR=/pika/source
ARG BUILD_DIR=/pika/build

ARG CMAKE_COMMON_FLAGS
ARG CMAKE_FLAGS

COPY . ${SOURCE_DIR}

# Configure & Build
RUN spack build-env $spack_spec -- bash -c "cmake -B${BUILD_DIR} ${SOURCE_DIR} \
    $CMAKE_COMMON_FLAGS $CMAKE_FLAGS && cmake --build ${BUILD_DIR} --target all tests examples"
