ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG SPACK_SPEC
ENV spack_spec $SPACK_SPEC
# Install dependencies for this configuration
RUN spack env create pika_ci && \
    spack -e pika_ci add $spack_spec && \
    spack -e pika_ci install --fail-fast --only dependencies $spack_spec && \
    spack -e pika_ci clean --all
