# Copyright (c) 2023 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file BOOST_LICENSE_1_0.rst or copy at http://www.boost.org/LICENSE_1_0.txt)

include:
  #  - local: '.gitlab/includes/dockerhub_pipeline.yml'
  #  - local: '.gitlab/includes/gcc9_pipeline.yml'
  #  - local: '.gitlab/includes/gcc9_cuda11_pipeline.yml'
  #  - local: '.gitlab/includes/gcc11_pipeline.yml'
  #  - local: '.gitlab/includes/gcc12_pipeline.yml'
  #  - local: '.gitlab/includes/gcc12_cuda12_pipeline.yml'
  #  - local: '.gitlab/includes/gcc13_pipeline.yml'
  #  - local: '.gitlab/includes/clang11_pipeline.yml'
  #  - local: '.gitlab/includes/clang12_pipeline.yml'
  #  - local: '.gitlab/includes/clang13_pipeline.yml'
  #  - local: '.gitlab/includes/clang14_cuda11_pipeline.yml'
  #  - local: '.gitlab/includes/clang15_pipeline.yml'
  #  - local: '.gitlab/includes/clang16_pipeline.yml'
  #  - local: '.gitlab/includes/performance_gcc13_pipeline.yml'
  - local: '.gitlab/includes/hip_pipeline.yml'
